/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesStorymakerServiceRouteImport } from './routes/services/storymaker-service'
import { Route as ProductsStorymakerCourseRouteImport } from './routes/products/storymaker-course'
import { Route as ProductsImageEditorRouteImport } from './routes/products/image-editor'
import { Route as ProductsContractRouteImport } from './routes/products/contract'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStorymakerServiceRoute =
  ServicesStorymakerServiceRouteImport.update({
    id: '/services/storymaker-service',
    path: '/services/storymaker-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsStorymakerCourseRoute =
  ProductsStorymakerCourseRouteImport.update({
    id: '/products/storymaker-course',
    path: '/products/storymaker-course',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsImageEditorRoute = ProductsImageEditorRouteImport.update({
  id: '/products/image-editor',
  path: '/products/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsContractRoute = ProductsContractRouteImport.update({
  id: '/products/contract',
  path: '/products/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/contract': typeof ProductsContractRoute
  '/products/image-editor': typeof ProductsImageEditorRoute
  '/products/storymaker-course': typeof ProductsStorymakerCourseRoute
  '/services/storymaker-service': typeof ServicesStorymakerServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/contract': typeof ProductsContractRoute
  '/products/image-editor': typeof ProductsImageEditorRoute
  '/products/storymaker-course': typeof ProductsStorymakerCourseRoute
  '/services/storymaker-service': typeof ServicesStorymakerServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/contract': typeof ProductsContractRoute
  '/products/image-editor': typeof ProductsImageEditorRoute
  '/products/storymaker-course': typeof ProductsStorymakerCourseRoute
  '/services/storymaker-service': typeof ServicesStorymakerServiceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/contract'
    | '/products/image-editor'
    | '/products/storymaker-course'
    | '/services/storymaker-service'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/contract'
    | '/products/image-editor'
    | '/products/storymaker-course'
    | '/services/storymaker-service'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/products/contract'
    | '/products/image-editor'
    | '/products/storymaker-course'
    | '/services/storymaker-service'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsContractRoute: typeof ProductsContractRoute
  ProductsImageEditorRoute: typeof ProductsImageEditorRoute
  ProductsStorymakerCourseRoute: typeof ProductsStorymakerCourseRoute
  ServicesStorymakerServiceRoute: typeof ServicesStorymakerServiceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/storymaker-service': {
      id: '/services/storymaker-service'
      path: '/services/storymaker-service'
      fullPath: '/services/storymaker-service'
      preLoaderRoute: typeof ServicesStorymakerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/storymaker-course': {
      id: '/products/storymaker-course'
      path: '/products/storymaker-course'
      fullPath: '/products/storymaker-course'
      preLoaderRoute: typeof ProductsStorymakerCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/image-editor': {
      id: '/products/image-editor'
      path: '/products/image-editor'
      fullPath: '/products/image-editor'
      preLoaderRoute: typeof ProductsImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/contract': {
      id: '/products/contract'
      path: '/products/contract'
      fullPath: '/products/contract'
      preLoaderRoute: typeof ProductsContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsContractRoute: ProductsContractRoute,
  ProductsImageEditorRoute: ProductsImageEditorRoute,
  ProductsStorymakerCourseRoute: ProductsStorymakerCourseRoute,
  ServicesStorymakerServiceRoute: ServicesStorymakerServiceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
