/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorymakerServiceRouteImport } from './routes/storymaker-service'
import { Route as StorymakerCourseRouteImport } from './routes/storymaker-course'
import { Route as ImageEditorRouteImport } from './routes/image-editor'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as IndexRouteImport } from './routes/index'

const StorymakerServiceRoute = StorymakerServiceRouteImport.update({
  id: '/storymaker-service',
  path: '/storymaker-service',
  getParentRoute: () => rootRouteImport,
} as any)
const StorymakerCourseRoute = StorymakerCourseRouteImport.update({
  id: '/storymaker-course',
  path: '/storymaker-course',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditorRoute = ImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/image-editor': typeof ImageEditorRoute
  '/storymaker-course': typeof StorymakerCourseRoute
  '/storymaker-service': typeof StorymakerServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/image-editor': typeof ImageEditorRoute
  '/storymaker-course': typeof StorymakerCourseRoute
  '/storymaker-service': typeof StorymakerServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/image-editor': typeof ImageEditorRoute
  '/storymaker-course': typeof StorymakerCourseRoute
  '/storymaker-service': typeof StorymakerServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract'
    | '/image-editor'
    | '/storymaker-course'
    | '/storymaker-service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract'
    | '/image-editor'
    | '/storymaker-course'
    | '/storymaker-service'
  id:
    | '__root__'
    | '/'
    | '/contract'
    | '/image-editor'
    | '/storymaker-course'
    | '/storymaker-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractRoute: typeof ContractRoute
  ImageEditorRoute: typeof ImageEditorRoute
  StorymakerCourseRoute: typeof StorymakerCourseRoute
  StorymakerServiceRoute: typeof StorymakerServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storymaker-service': {
      id: '/storymaker-service'
      path: '/storymaker-service'
      fullPath: '/storymaker-service'
      preLoaderRoute: typeof StorymakerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storymaker-course': {
      id: '/storymaker-course'
      path: '/storymaker-course'
      fullPath: '/storymaker-course'
      preLoaderRoute: typeof StorymakerCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-editor': {
      id: '/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof ImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractRoute: ContractRoute,
  ImageEditorRoute: ImageEditorRoute,
  StorymakerCourseRoute: StorymakerCourseRoute,
  StorymakerServiceRoute: StorymakerServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
